// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/billing/billing.proto

package billing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() {
	proto.RegisterFile("proto/billing/billing.proto", fileDescriptor_billing_cea56e83fa202548)
}

var fileDescriptor_billing_cea56e83fa202548 = []byte{
	// 44 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xca, 0xcc, 0xc9, 0xc9, 0xcc, 0x4b, 0x87, 0xd1, 0x7a, 0x60, 0x51, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x34, 0xe9, 0x8e, 0x49, 0x1d, 0x00, 0x00, 0x00,
}
