apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-canary
  name: web-canary
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    load-balancer-web-canary: "true"
  sessionAffinity: None
  type: LoadBalancer
