// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/settlement/settlement.proto

package settlement

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() {
	proto.RegisterFile("proto/settlement/settlement.proto", fileDescriptor_settlement_d4e8067cd9ae7696)
}

var fileDescriptor_settlement_d4e8067cd9ae7696 = []byte{
	// 47 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x29, 0xc9, 0x49, 0xcd, 0x4d, 0xcd, 0x2b, 0x41, 0x62, 0xea, 0x81,
	0xe5, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x30, 0x47, 0x34, 0x23, 0x00, 0x00, 0x00,
}
